#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

setbg &			      # set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &  # Uncomment to use Xresources colors/settings on startup
mpd &			      # music player daemon-you might prefer it as a service though
remaps &		      # run the remaps script, switching caps/esc and more; check it for more info
xcompmgr &		                 # xcompmgr for transparency
dunst &			                 # dunst for notifications
xset r rate 300 50 &             # Speed xrate up
unclutter &		                 # Remove mouse when idle

redshift -l 48.8924:2.2153 &     # Provides night light (Paris coordinates)
#spotify-adskip >/dev/null 2>&1 & # Restarts Spotify when it plays an ad
#pulseeffects &


# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
